[versions]

androidGradlePlugin = "8.3.1"
kotlin = "1.9.23"
gradle = "8.3.1"
hilt = "2.51.1"
androidxCore = "1.12.0"
androidxCoreSplashscreen = "1.0.1"
androidxComposeCompiler = "1.5.8"
detekt = "1.23.6"
androidxComposeBom = "2024.03.00"
accompanist = "0.34.0"
activity-compose = "1.8.2"
androidx-junit = "1.1.5"
appcompat = "1.6.1"
core-testing = "2.2.0"
espresso-core = "3.5.1"
hilt-navigation-compose = "1.2.0"
junit = "4.13.2"
kotlinx-coroutines-android = "1.8.0"
lifecycle-viewmodel-compose = "2.7.0"
logging-interceptor = "4.12.0"
mockk = "1.13.10"
navigation-compose = "2.7.7"
retrofit = "2.11.0"
ksp = "1.9.23-1.0.19"
truth = "1.4.2"
turbine = "1.1.0"
leakcanary = "2.13"
secrets = "2.0.1"
kotlin1920 = "1.9.23"
material = "1.11.0"
uiTooling = "1.6.4"
moshi = "1.15.1"
moshi-converter = "2.11.0"
doctor = "0.9.2"

[libraries]

leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

androidx-compose-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-viewmodel-compose" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "core-testing" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material = { module = "androidx.compose.material:material" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
accompanist-systemui-controller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }
# Detekt
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
coil = "io.coil-kt:coil-compose:2.6.0"
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-android" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshi-converter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "moshi-converter" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
junit = { module = "junit:junit", version.ref = "junit" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
doctor = { id = "com.osacky.doctor", version.ref = "doctor" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }

# Plugins defined by this project
timetotrade-android-application = { id = "timetotrade.android.application", version = "unspecified" }
timetotrade-android-application-compose = { id = "timetotrade.android.application.compose", version = "unspecified" }
timetotrade-android-hilt = { id = "timetotrade.android.hilt", version = "unspecified" }
timetotrade-android-moshi = { id = "timetotrade.android.moshi", version = "unspecified" }
timetotrade-android-library = { id = "timetotrade.android.library", version = "unspecified" }
timetotrade-android-library-compose = { id = "timetotrade.android.library.compose", version = "unspecified" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin1920" }

[bundles]
compose = [
    "androidx-activity-compose"
]
